// <auto-generated />
using System;
using AbmPaises.Web.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AbmPaises.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190812143515_InitialDb2.3")]
    partial class InitialDb23
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AbmPaises.Web.Data.Entities.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreCiudad");

                    b.Property<int?>("PaisID");

                    b.Property<int?>("ProvinciaId");

                    b.HasKey("Id");

                    b.HasIndex("PaisID");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("AbmPaises.Web.Data.Entities.Pais", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreCiudad")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("NombrePais")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("NombreProvincia")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("AbmPaises.Web.Data.Entities.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreProvincia")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("PaisID");

                    b.HasKey("Id");

                    b.HasIndex("PaisID");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("AbmPaises.Web.Data.Entities.Ciudad", b =>
                {
                    b.HasOne("AbmPaises.Web.Data.Entities.Pais")
                        .WithMany("Ciudades")
                        .HasForeignKey("PaisID");

                    b.HasOne("AbmPaises.Web.Data.Entities.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId");
                });

            modelBuilder.Entity("AbmPaises.Web.Data.Entities.Provincia", b =>
                {
                    b.HasOne("AbmPaises.Web.Data.Entities.Pais", "Pais")
                        .WithMany("Provincias")
                        .HasForeignKey("PaisID");
                });
#pragma warning restore 612, 618
        }
    }
}
